# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('client_id', models.TextField(null=True)),
                ('client_secret', models.TextField(null=True)),
                ('access_token', models.TextField(null=True)),
                ('params', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='論理削除フラグ')),
            ],
        ),
        migrations.RemoveField(
            model_name='sourcecode',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sourcecode',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='sourcecode',
            name='params',
        ),
    ]
